### ISSUE TITLE
Unable to access the dataset through Huggingface or datasets.load_dataset

### ISSUE THREAD

**Issue by JasonShao55** [microsoft/XGLUE#7]
Here's the error I had when trying to download the dataset by `datasets.load_dataset` in python:

```python
Traceback (most recent call last):
  File "D:\OneDrive\Learning\NLP Chinese FLAN\778 XGLUE code\778 code.py", line 135, in <module>
    dataset = load_dataset('xglue', 'nc')
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\load.py", line 1797, in load_dataset
    builder_instance.download_and_prepare(
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\builder.py", line 890, in download_and_prepare
    self._download_and_prepare(
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\builder.py", line 1649, in _download_and_prepare
    super()._download_and_prepare(
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\builder.py", line 963, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "C:\Users\ASUS\.cache\huggingface\modules\datasets_modules\datasets\xglue\8566eedecd9ab28e01c051c023dadf97bf408e5195f76b06aba70ebd4697ae08\xglue.py", line 475, in _split_generators
    archive = dl_manager.download(_XGLUE_ALL_DATA)
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\download\download_manager.py", line 427, in download
    downloaded_path_or_paths = map_nested(
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\utils\py_utils.py", line 435, in map_nested
    return function(data_struct)
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\download\download_manager.py", line 453, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\utils\file_utils.py", line 183, in cached_path
    output_path = get_from_cache(
  File "D:\Users\ASUS\anaconda3\envs\conda1.0\lib\site-packages\datasets\utils\file_utils.py", line 568, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} (error {response.status_code})")
ConnectionError: Couldn't reach https://xglue.blob.core.windows.net/xglue/xglue_full_dataset.tar.gz (error 409)

Process finished with exit code 1
```
Also the previewer on huggingface is not available:

```
Cannot load the dataset split (in streaming mode) to extract the first rows.
Error code:   StreamingRowsError
Exception:    FileNotFoundError
Message:      https://xglue.blob.core.windows.net/xglue/xglue_full_dataset.tar.gz
Traceback:    Traceback (most recent call last):
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/implementations/http.py", line 417, in _info
                  await _file_info(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/implementations/http.py", line 837, in _file_info
                  r.raise_for_status()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
                  raise ClientResponseError(
              aiohttp.client_exceptions.ClientResponseError: 409, message='Public access is not permitted on this storage account.', url=URL('https://xglue.blob.core.windows.net/xglue/xglue_full_dataset.tar.gz')
              
              The above exception was the direct cause of the following exception:
              
              Traceback (most recent call last):
                File "/src/services/worker/src/worker/utils.py", line 260, in get_rows_or_raise
                  return get_rows(
                File "/src/services/worker/src/worker/utils.py", line 201, in decorator
                  return func(*args, **kwargs)
                File "/src/services/worker/src/worker/utils.py", line 238, in get_rows
                  rows_plus_one = list(itertools.islice(ds, rows_max_number + 1))
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 1353, in __iter__
                  for key, example in ex_iterable:
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/iterable_dataset.py", line 207, in __iter__
                  yield from self.generate_examples_fn(**self.kwargs)
                File "/tmp/modules-cache/datasets_modules/datasets/xglue/8566eedecd9ab28e01c051c023dadf97bf408e5195f76b06aba70ebd4697ae08/xglue.py", line 518, in _generate_examples
                  for path, file in archive:
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 881, in __iter__
                  yield from self.generator(*self.args, **self.kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 932, in _iter_from_urlpath
                  with xopen(urlpath, "rb", use_auth_token=use_auth_token) as f:
                File "/src/services/worker/.venv/lib/python3.9/site-packages/datasets/download/streaming_download_manager.py", line 506, in xopen
                  file_obj = fsspec.open(file, mode=mode, *args, **kwargs).open()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 134, in open
                  return self.__enter__()
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/core.py", line 102, in __enter__
                  f = self.fs.open(self.path, mode=mode)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/spec.py", line 1199, in open
                  f = self._open(
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/implementations/http.py", line 356, in _open
                  size = size or self.info(path, **kwargs)["size"]
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/asyn.py", line 115, in wrapper
                  return sync(self.loop, func, *args, **kwargs)
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/asyn.py", line 100, in sync
                  raise return_result
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/asyn.py", line 55, in _runner
                  result[0] = await coro
                File "/src/services/worker/.venv/lib/python3.9/site-packages/fsspec/implementations/http.py", line 430, in _info
                  raise FileNotFoundError(url) from exc
              FileNotFoundError: https://xglue.blob.core.windows.net/xglue/xglue_full_dataset.tar.gz
```

Perhaps this has something to do with the permission configuration of access?

**Comment by Eureka6174** [comment]
You can download it from: https://1drv.ms/u/s!Amt8n9AJEyxchJtmUXkNFaTXLCbVOQ?e=2jYlMZ.

**Comment by JasonShao55** [comment]
Hi, thanks for your reply.

We checked it out and found most of the subsets are not parsable due to format reasons and decided not to work on it. Thanks anyway.
